import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const errs = []; page.on('pageerror', (e) => errs.push(e.message)); page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await page.goto('http://localhost:5199/#test', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.evaluate(() => window.__city.start());
const info = () => page.evaluate(() => window.__city.info());
await page.evaluate(() => { const c = window.__city; c.time(0.45); c.weather(0); c.free(); c.teleport(108, 0, 130); c.look(2.6, 0.05); });
await page.waitForTimeout(1500);
await page.keyboard.press('Space'); await page.waitForTimeout(150);
await page.keyboard.press('Space'); await page.waitForTimeout(300);
let i = await info(); console.log('takeoff flying', i.flying, i.pos);
await page.keyboard.down('Space'); await page.waitForTimeout(1500); await page.keyboard.up('Space');
i = await info(); console.log('rise', i.flying, i.pos);
await page.screenshot({ path: 'shots/fly_hover.png' });
await page.keyboard.down('KeyW'); await page.keyboard.down('ShiftLeft'); await page.waitForTimeout(3000);
i = await info(); console.log('boost', i.flying, i.pos);
await page.screenshot({ path: 'shots/fly_boost.png' });
await page.keyboard.up('ShiftLeft'); await page.keyboard.up('KeyW');
await page.waitForTimeout(1500);
await page.keyboard.down('KeyC'); await page.waitForTimeout(6000); await page.keyboard.up('KeyC');
i = await info(); console.log('after C', i.flying, i.pos);
// F stops flight
await page.keyboard.press('Space'); await page.waitForTimeout(150); await page.keyboard.press('Space'); await page.waitForTimeout(200);
await page.keyboard.down('Space'); await page.waitForTimeout(800); await page.keyboard.up('Space');
console.log('refly', (await info()).flying);
await page.keyboard.press('KeyF'); await page.waitForTimeout(200);
console.log('after F', (await info()).flying);
console.log('errors', errs);
await browser.close();
